// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRopi_BSnrKWXaTthqKRHKjo1w_htO3E',
    appId: '1:590989361304:web:c79d4e873d0c683e5890ed',
    messagingSenderId: '590989361304',
    projectId: 'fewproj-c945f',
    authDomain: 'fewproj-c945f.firebaseapp.com',
    storageBucket: 'fewproj-c945f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIMNiibXqVxJtS7De22gCsGheQZaQpEFc',
    appId: '1:590989361304:android:af0e3bc08a6a6b6e5890ed',
    messagingSenderId: '590989361304',
    projectId: 'fewproj-c945f',
    storageBucket: 'fewproj-c945f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwVWfufaozReKCtw63xIrehdv4okjZAGc',
    appId: '1:590989361304:ios:1246460fd10b7a865890ed',
    messagingSenderId: '590989361304',
    projectId: 'fewproj-c945f',
    storageBucket: 'fewproj-c945f.appspot.com',
    iosBundleId: 'com.msu.testdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwVWfufaozReKCtw63xIrehdv4okjZAGc',
    appId: '1:590989361304:ios:1246460fd10b7a865890ed',
    messagingSenderId: '590989361304',
    projectId: 'fewproj-c945f',
    storageBucket: 'fewproj-c945f.appspot.com',
    iosBundleId: 'com.msu.testdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcRopi_BSnrKWXaTthqKRHKjo1w_htO3E',
    appId: '1:590989361304:web:8f7d8c29c27ac40a5890ed',
    messagingSenderId: '590989361304',
    projectId: 'fewproj-c945f',
    authDomain: 'fewproj-c945f.firebaseapp.com',
    storageBucket: 'fewproj-c945f.appspot.com',
  );
}
